Server:
  RunMode: debug
  HttpPort: 8866
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8866/static
  UploadImageMaxSize: 5 # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
  DefaultContextTimeout: 60
Database:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 192.168.1.43:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: fenghu
  Issuer: blog-service
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxx@qq.com
  Password: xxxx
  IsSSL: true
  From: xxx@qq.com
  To:
    - xxx@qq.com

